export const EVENT_TYPE = {
  CHARITY: "CHARITY",
  VOLUNTEER: "VOLUNTEER",
  DONATION: "DONATION",
  ASSISTANCE: "ASSISTANCE",
};

export const EVENT_STATUS = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  INPROGRESS: "INPROGRESS",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
};
