export const SUPPORT_TICKET_TYPE = {
  EVENTS: "EVENTS",
  DONATIONS: "TRANSACTIONS"
};


export const SUPPORT_TICKET_STATUS = {
  OPEN: "OPEN",
  ACTIVE: "ACTIVE",
  COMPLETED: "COMPLETED",
  CLOSED: "CLOSED"
};
